# Generated by Django 4.2.4 on 2023-08-02 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large'), ('XL', 'XL')], default=None, max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=19)),
            ],
        ),
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(default=None, max_length=30)),
                ('fabric', models.CharField(default=None, max_length=20)),
                ('sku', models.CharField(default=None, max_length=20)),
                ('is_imported', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shirt.category')),
            ],
        ),
    ]
